### ISSUE TITLE
Unable to canonicalize address

### ISSUE THREAD

**Issue by hatamiarash7** [confluentinc/confluent-kubernetes-examples#132]
Hey there

I have a little problem here with the `single-node` example. There is an error in `Kafka` pod :

```
[WARN] 2022-04-26 14:29:47,008 [main-SendThread(zookeeper.confluent.svc.cluster.local:2181)] org.apache.zookeeper.ClientCnxn run - Session 0x0 for sever zookeeper.confluent.svc.cluster.local:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.lang.IllegalArgumentException: Unable to canonicalize address zookeeper.confluent.svc.cluster.local:2181 because it's not resolvable
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:78)
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1161)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1210)
[INFO] 2022-04-26 14:29:47,273 [main] kafka.zookeeper.ZooKeeperClient info - [ZooKeeperClient Kafka server] Closing.
[ERROR] 2022-04-26 14:29:48,112 [main-SendThread(zookeeper.confluent.svc.cluster.local:2181)] org.apache.zookeeper.client.StaticHostProvider resolve - Unable to resolve address: zookeeper.confluent.svc.cluster.local:2181
java.net.UnknownHostException: zookeeper.confluent.svc.cluster.local
```

Error messages :

```
Unable to canonicalize address zookeeper.confluent.svc.cluster.local:2181 because it's not resolvable
Unable to resolve address: zookeeper.confluent.svc.cluster.local:2181
```

I checked my `zookeper` ... it's good and works without a problem. What can I do?

**Comment by cjd9** [comment]
Had a similar error with my juberenetes setup. The problem was i set the ZOOKEEPER_HOST as `zookeeper-service` . when i renamed it to just `zookeeper` or any other name that does not contain a hyphen (`-`) , it finally worked. Maybe the kafka setup does not see `zookeeper.confluent.svc.cluster.local` as an valid host or url
