### ISSUE TITLE
Can't connect with Flink client from operator via minikube with loadbalancer

### ISSUE THREAD

**Issue by colin-williams** [confluentinc/confluent-kubernetes-examples#198]
I am evaluating the confluent operator as a developer. I have been trying to connect to the kafka server via my local IDE using Apache Flink, for a few days. I have gone through some of the networking examples and configured load balancers similar to what is shown in https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/networking/external-access-load-balancer-deploy .

I am deploying confluent platform on minikube (mentioned in the examples). I noticed in my debugging logs that it looks like the kafka client is trying to connect to b0.minikube.domain. One thing I find interesting regarding this is the b0 host alias. It also looks like it's trying to use port 9092 when the loadbalncer port via minikube is configured otherwise.  I don't see this hostname b0 configured explicitly anywhere in confluent kubernetes helm charts. 

```
21:30:01,196 DEBUG org.apache.kafka.clients.NetworkClient                       [] - [Producer clientId=producer-9] Initialize connection to node b0.minikube.domain:9092 (id: 0 rack: 0) for sending metadata request
21:30:01,196 WARN  org.apache.kafka.clients.NetworkClient                       [] - [Producer clientId=producer-9] Error connecting to node b0.minikube.domain:9092 (id: 0 rack: 0)
java.net.UnknownHostException: b0.minikube.domain
    at [java.net](http://java.net/).InetAddress$CachedAddresses.get(InetAddress.java:797) ~[?:?]
    at [java.net](http://java.net/).InetAddress.getAllByName0(InetAddress.java:1519) ~[?:?]
    at [java.net](http://java.net/).InetAddress.getAllByName(InetAddress.java:1378) ~[?:?]
    at [java.net](http://java.net/).InetAddress.getAllByName(InetAddress.java:1306) ~[?:?]
    at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27) ~[kafka-clients-3.2.3.jar:?]
    at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110) ~[kafka-clients-3.2.3.jar:?]
    at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:511) ~[kafka-clients-3.2.3.jar:?]
    at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:468) ~[kafka-clients-3.2.3.jar:?]
    at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173) ~[kafka-clients-3.2.3.jar:?]
    at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:988) ~[kafka-clients-3.2.3.jar:?]
    at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73) ~[kafka-clients-3.2.3.jar:?]
    at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1161) ~[kafka-clients-3.2.3.jar:?]
    at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1049) ~[kafka-clients-3.2.3.jar:?]
    at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558) ~[kafka-clients-3.2.3.jar:?]
    at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:328) ~[kafka-clients-3.2.3.jar:?]
    at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243) ~[kafka-clients-3.2.3.jar:?]
    at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by OneCricketeer** [comment]
Rather than using Flink, have you tried debugging first with cli tools like `kcat -L` commsnd?

**Comment by MosheBlumbergX** [comment]
the `b` is the default for the broker prefix, as outlined in the doc you've shared: 

```
The prefixes are used for external DNS hostnames. In this tutorial, Kafka bootstrap server will use the default prefix, kafka, and the brokers will use the default prefix, b.
```

To get access from your local IDE in a minikube cluster I suspect you will have to add the DNS entries to the host name, for the LB, and each broker. 

```
    kafka.$DOMAIN for the bootstrap server
    b0.$DOMAIN for the broker #1
    b1.$DOMAIN for the broker #2
    b2.$DOMAIN for the broker #3
```

The 9092, is the normal external port.

**Comment by MosheBlumbergX** [comment]
Closing this issue as stale.
