### ISSUE TITLE
Image cp-server cannot be replaced with cp-kafka

### ISSUE THREAD

**Issue by rafaelklossner** [confluentinc/confluent-kubernetes-examples#206]
Hello,

I have tried to use CFK with cp-kafka instead of cp-server. According to [https://hub.docker.com/r/confluentinc/cp-server](url) the images should be replaceable (if no commercial features were used). 

The configuration I have tried is:
```---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-zookeeper:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 5Gi
  logVolumeCapacity: 1Gi
  storageClass:
    name: managed-azuredisk-standard-lrs
  authentication:
    type: digest
    jaasConfig:
      secretRef: authentication-credentials
  tls:
    secretRef: kafka-tls
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-kafka:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  configOverrides:
    server:
      - authorizer.class.name=kafka.security.authorizer.AclAuthorizer
  dataVolumeCapacity: 5Gi
  storageClass:
    name: managed-azuredisk-standard-lrs
  metricReporter:
    enabled: false
  tls:
    secretRef: kafka-tls
  listeners:
    internal:
      authentication:
        type: plain
        jaasConfig:
          secretRef: authentication-credentials
      tls:
        enabled: true
    external:
      authentication:
        type: plain
        jaasConfig:
          secretRef: authentication-credentials
      tls:
        enabled: true
      externalAccess:
        type: loadBalancer
        loadBalancer:
          domain: my.domain
          advertisedPort: 30129
          brokerPrefix: kafka-
          bootstrapPrefix: kafka
  authorization:
    type: simple
    superUsers:
      - User:admin
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2182
      authentication:
        type: digest
        jaasConfig:
          secretRef: authentication-credentials
      tls:
        enabled: true
```

With `authentication-credentials` secret containing (with the according content):
* digest-users.json
* digest.txt
* plain-users.json
* plain.txt

With cp-server image this works. But with cp-kafka, the follwing exception is thrown:
```
[ERROR] 2023-01-19 10:58:23,889 [main] kafka.server.KafkaServer error - [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown
org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: No LoginModule found for io.confluent.kafka.server.plugins.auth.FileBasedLoginModule
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at kafka.server.BrokerToControllerChannelManagerImpl.newRequestThread(BrokerToControllerChannelManager.scala:188)
	at kafka.server.BrokerToControllerChannelManagerImpl.<init>(BrokerToControllerChannelManager.scala:167)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:286)
	at kafka.Kafka$.main(Kafka.scala:109)
	at kafka.Kafka.main(Kafka.scala)
Caused by: javax.security.auth.login.LoginException: No LoginModule found for io.confluent.kafka.server.plugins.auth.FileBasedLoginModule
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:731)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:672)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:670)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:670)
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:581)
	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:60)
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:170)
	... 7 more
```
As it turns out, by letting the CFK operator manage the users, the FileBasedLoginModule seems to be required. 

Is there a workaround for this? Has someone tried to use cp-kafka in combination with CFK?

**Comment by MosheBlumbergX** [comment]
The `FileBasedLoginModule` is part of the confluent server package and not the open source Kafka, CFK uses this modile t extract the user from the files mounted via the secrets.

The docs outline support ONLY for confluent server 

https://docs.confluent.io/platform/current/installation/versions-interoperability.html#co-long

```
Available, only via Confluent Server
```   

You can probably attempt some config overrides though.
